function y = problem002(x)
%% Project Euler - Problem 2
%
% Each new term in the Fibonacci sequence is generated by adding the
% previous two terms. By starting with 1 and 2, the first 10 terms will be:
% 	 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%
% By considering the terms in the Fibonacci sequence whose values do not
% exceed four million, find the sum of the even-valued terms.

%% Solution
%  0 1 1 2 3 5 8 13 21 34 55 89 144
%  *     *     *       *        *
% every third Fibonacci number (starting from 2) is even.
%       0 2  8   34  144  610
% sum:  0 2  10  44  188  798

%% two consecutive even Fibonacci numbers [a a2] out of sequence: a1 b1 b2 a2 b3 b4 a3
% b1 = (a2 - a1)/2
% b2 = a1 + b1 =   (a1 + a2)/2
% b3 = b2 + a2 =   (a1 + a2*3)/2
% b4 = a2 + b3 =   (a1 + a2*5)/2
% a3 = b3 + b4 					=    a1 +  4*a2

	a1 = 2;
	a2 = 0;
	
	y=0;
	while(a2<x)
		y=y+a2;
		[a1, a2]=nextfib2(a1,a2);
	end
end
function [a2 a3] = nextfib2(a1,a2)
	a3 = a1+4*a2;
end
